language: swift
osx_image: xcode10.2.1

script:
- set -o pipefail
- xcodebuild -project XcodeOpener/XcodeOpener.xcodeproj -scheme XcodeOpener -destination platform\=macOS build | xcpretty

notifications:
  slack: $SLACK_CHANNEL